dataset:
  dataset: MNIST
  path: './'
  subclass:
  subset: 2560
  return_index: True
  batch_size: 256

training:
  lr: 1.0e-4
  epochs: 500
  n_iter: 2000
  n_samples: 40000
  n_xchunk: 20
  n_zchunk: 100
  device: cuda
  save: OTAE_mnist.pth
  seed: 1234

model:
  num_data: 2560
  epsilon: 1
  in_channels: 1
  latent_dim: 5
  activation: lrelu
  img_size: 28
  maxiter: 1
  device: cuda
  n_channels: 
